<a href="https://colab.research.google.com/github/RodrigoGuedesDP/IA/blob/main/01_Introduccion_a_Python/06_numpy_arrays_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://www.ctic.uni.edu.pe/wp-content/uploads/2022/04/588px-x-348px-web-1.png" alt="HTML5 Icon" width="900" height="350" >


# **NumPy Arrays**


**Objetivo**

El objetivo de este laboratorio es brindar una comprensión profunda y práctica de la biblioteca NumPy en Python, una herramienta esencial para el cálculo numérico y el análisis en data science.


**Índice del Laboratorio**

- 1. Introducción y Configuración
- 2. Creación de Arrays
- 3. Propiedades de los Arrays
- 4. Operaciones Básicas
- 5. Indexación y Slicing
- 6. Manipulación de la Forma
- 7. Broadcasting
- 8. Álgebra Lineal


## 1. Introducción y Configuración

**¿Qué es NumPy?**

NumPy (Numerical Python) es una librería esencial en Python para el cálculo numérico y el análisis de datos. Proporciona:


- **Arrays multidimensionales:** Estructuras de datos eficientes para almacenar y manipular grandes conjuntos de datos numéricos.
- **Funciones matemáticas:** Operaciones vectorizadas para realizar cálculos rápidos y eficientes.
- **Herramientas avanzadas:** Funciones para álgebra lineal, transformadas de Fourier, generación de números aleatorios, y más.


**Instalación y Configuración**

Antes de comenzar, asegúrate de tener NumPy instalado en tu entorno de Python. Puedes instalarlo usando pip:

In [ ]:
!pip3 install numpy==1.26.1



In [ ]:
import numpy as np

In [ ]:
#Revisar la version de una libreria
np.__version__


'1.26.1'

In [ ]:
# Instalación
!pip3 install numpy

# Importación y verificación de versión
import numpy as np
print("Versión de NumPy:", np.__version__)


## 2. Creación de Arrays

Los arrays son la base de NumPy y representan colecciones de elementos del mismo tipo de datos. Veamos cómo crearlos de diferentes maneras.

### 2.1. Crear un Array desde una Lista



In [ ]:
np.array([[1, 3, 4, 5, 6, 8],
          [1, 3, 4, 5, 5,7]])

array([[1, 3, 4, 5, 6, 8],
       [1, 3, 4, 5, 5, 7]])

**Ejemplo 1:** Array Unidimensional

In [ ]:
# Array unidimensional desde una lista
array_1d = np.array([10, 20, 30, 40])
print("Array 1D:", array_1d)
array_1d.shape


Array 1D: [10 20 30 40]


(4,)

**Ejemplo 2:** Array Multidimensional


In [ ]:
# Array bidimensional desde una lista de listas
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Array 2D:\n", array_2d)
array_2d.shape

Array 2D:
 [[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
#array con matriz 3x3
array_3d = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])
array_3d.shape

(3, 3)

In [ ]:
array_4d = np.array([[[1,2,3],
          [4,5,6],
          [7,8,9]],
           [[1,2,3],
          [4,5,6],
          [7,8,9]]])
array_4d.shape

(2, 3, 3)

In [ ]:
array_3d = np.array([[[1,2,3],
          [4,5,6],
          [7,8,9]],
           [[1,2,3],
          [4,5,6],
          [7,8,9]],[[1,2,3],
          [4,5,6],
          [7,8,9]]])
array_3d.shape

(3, 3, 3)

**Ejercicios**

Crea un array unidimensional con los números del 5 al 15.


In [ ]:
array_1d =np.array(range(5,16))

Genera un array bidimensional de 2 filas y 3 columnas con números decimales.


In [ ]:
array_2d = np.random.rand(2, 3)
print(array_2d)
array_2d.shape

[[0.30724187 0.17321031 0.05110355]
 [0.91138289 0.02765731 0.63617367]]


(2, 3)

Crea un array tridimensional de forma (2, 2, 2) con números enteros.

In [ ]:
array_3d = np.random.randint(0, 100, size = (2, 2, 2))

### 2.2. Arrays Predefinidos

NumPy ofrece funciones para crear arrays con valores predefinidos, lo cual es útil para inicializar matrices o vectores.

**Ejemplo 1:** Arrays de Ceros y Unos

In [ ]:
# Array de ceros de forma (3, 3)
zeros_array = np.zeros((3, 3))
print("Array de ceros:\n", zeros_array)

# Array de unos de forma (2, 4)
ones_array = np.ones((2, 4))
print("Array de unos:\n", ones_array)


**Ejemplo 2:** Array de Valores Constantes


In [ ]:
# Array lleno con el valor 7 de forma (3, 2)
full_array = np.full((3, 2), 7)
print("Array lleno de 7:\n", full_array)


**Ejercicios**

Crea un array de ceros de forma (5, 5).


In [ ]:
zeros_array = np.zeros((5,5))
zeros_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

NameError: name 'size' is not defined

Genera un array de unos de forma (4, 1).


In [ ]:
array_de_unos = np.ones((4,1))
array_de_unos

array([[1.],
       [1.],
       [1.],
       [1.]])

Crea un array lleno con el número pi (π) de forma (2, 3).

In [ ]:
full_array = np.full((2, 3), np.pi)
full_array

array([[3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265]])

### 2.3. Arrays con Rangos

Puedes crear arrays con secuencias de números utilizando funciones como arange y linspace.

**Ejemplo 1:** Usando arange


In [ ]:
# Números del 0 al 9
arange_array = np.arange(10)
print("Array con arange:", arange_array)

# Números del 5 al 20 con paso de 3
step_array = np.arange(5, 21, 3)
print("Array con paso de 3:", step_array)


Array con arange: [0 1 2 3 4 5 6 7 8 9]
Array con paso de 3: [ 5  8 11 14 17 20]


**Ejemplo 2:** Usando linspace


In [ ]:
# 5 números igualmente espaciados entre 0 y 1
linspace_array = np.linspace(0, 1, 5)
print("Array con linspace:", linspace_array)

# 4 números igualmente espaciados entre 10 y 50
linspace_array2 = np.linspace(10, 50, 4)
print("Otro array con linspace:", linspace_array2)


Array con linspace: [0.   0.25 0.5  0.75 1.  ]
Otro array con linspace: [10.         23.33333333 36.66666667 50.        ]


**Ejercicios**

Crea un array con números del 0 al 50, cada 5 unidades.


In [ ]:
array_1 = np.arange(0, 51, 5)
array_1

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

Genera un array con 7 números igualmente espaciados entre 2 y 3.


In [ ]:
array_2 = np.linspace(2, 3, 7)
array_2

array([2.        , 2.16666667, 2.33333333, 2.5       , 2.66666667,
       2.83333333, 3.        ])

Crea un array con números enteros del 10 al 1 en orden descendente.

In [ ]:
array_3 = np.arange(10, 0, -1)

## 2.4. Arrays Aleatorios

NumPy incluye funciones para generar arrays con números aleatorios, lo cual es útil en simulaciones y pruebas.



**Ejemplo 1:** Números Aleatorios Uniformes

In [ ]:
# Array de forma (2, 3) con números aleatorios entre 0 y 1
random_array = np.random.rand(2, 3)
print("Array aleatorio uniforme:\n", random_array)
random_array

Array aleatorio uniforme:
 [[0.5489723  0.75978427 0.35579889]
 [0.43092368 0.22082203 0.92229568]]


array([[0.5489723 , 0.75978427, 0.35579889],
       [0.43092368, 0.22082203, 0.92229568]])

**Ejemplo 2:** Números Aleatorios Enteros

In [ ]:
# Array de enteros aleatorios entre 1 y 100 de forma (3, 3)
random_int_array = np.random.randint(1, 100, (3, 3))
print("Array aleatorio de enteros:\n", random_int_array)


Array aleatorio de enteros:
 [[86 20 68]
 [56 31 93]
 [25 19 98]]


**Ejercicios**

Genera un array de forma (5,) con números aleatorios entre 0 y 1.


Crea un array de enteros aleatorios entre 50 y 100 de forma (4, 2).


Genera un array aleatorio de forma (3, 3) y multiplica todos sus elementos por 10.

###usando linspace

In [ ]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

## 3. Propiedades de los Arrays

Es importante comprender las propiedades de los arrays para manipularlos eficazmente.

**Ejemplo 1:** Explorando las Propiedades

In [ ]:
array = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", array)
print("Dimensiones (ndim):", array.ndim)
print("Forma (shape):", array.shape)
print("Tamaño total (size):", array.size)
print("Tipo de datos (dtype):", array.dtype)


**Ejemplo 2:** Tamaño en Memoria


In [ ]:
print("Tamaño en bytes de un elemento (itemsize):", array.itemsize)
print("Tamaño total en memoria (nbytes):", array.nbytes)


**Ejercicios**

Crea un array de forma (3, 4) y muestra todas sus propiedades.


Cambia el tipo de datos de un array a float64 y verifica el cambio en dtype.


Calcula el tamaño total en memoria de un array de forma (1000,) con tipo de datos int32.

## 4. Operaciones Básicas

Las operaciones vectorizadas en NumPy permiten realizar cálculos de forma eficiente sin necesidad de bucles.

### 4.1. Operaciones Matemáticas

**Ejemplo 1:** Operaciones Elemento a Elemento

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Suma:", a + b)
print("Resta:", a - b)
print("Multiplicación:", a * b)
print("División:", a / b)


**Ejemplo 2:** Operaciones con Escalares

In [ ]:
# Multiplicación por un escalar
scalar_mult = a * 10
print("Multiplicación por escalar:", scalar_mult)

# Exponenciación
exp_array = a ** 2
print("Exponenciación:", exp_array)


**Ejercicios**

Dado x = np.array([2, 4, 6]) y y = np.array([1, 3, 5]), calcula x * y y x / y.


Eleva al cubo cada elemento del array x.


Suma 5 a cada elemento del array y y luego calcula la raíz cuadrada.

### 4.2. Funciones Matemáticas

NumPy proporciona funciones universales (ufuncs) para realizar operaciones matemáticas.

**Ejemplo 1:** Funciones Estadísticas

In [ ]:
array = np.array([1, 5, 2, 8, 3])

print("Suma total:", array.sum())
print("Promedio:", array.mean())
print("Mediana:", np.median(array))
print("Desviación estándar:", array.std())


**Ejemplo 2:** Funciones Trigonométricas y Exponenciales

In [ ]:
angles = np.array([0, np.pi/2, np.pi])

print("Seno:", np.sin(angles))
print("Coseno:", np.cos(angles))
print("Exponencial:", np.exp(array))


**Ejercicios**

Calcula el valor máximo y mínimo de un array aleatorio de forma (10,).


Dado un array de ángulos en grados, conviértelos a radianes y calcula su seno.


Genera un array y normalízalo restando la media y dividiendo por la desviación estándar.

## 5. Indexación y Slicing

La indexación y el slicing te permiten acceder y modificar partes específicas de un array.

**Ejemplo 1:** Acceso a Elementos Individuales

In [ ]:
array = np.array([[10, 20, 30], [40, 50, 60]])

# Acceder al elemento en la fila 1, columna 2
element = array[1, 2]
print("Elemento en (1, 2):", element)


**Ejemplo 2:** Slicing de Subarrays

In [ ]:
# Obtener la primera fila
first_row = array[0, :]
print("Primera fila:", first_row)

# Obtener la segunda columna
second_col = array[:, 1]
print("Segunda columna:", second_col)

# Obtener un subarray de forma (2, 2)
subarray = array[:, :2]
print("Subarray:\n", subarray)


**Ejercicios**

Dado un array de forma (5, 5), extrae la submatriz central de forma (3, 3).


Cambia los elementos de la última fila de un array a ceros.


Invierte el orden de los elementos en un array unidimensional.


## 6. Manipulación de la Forma

### 6.1. Reshape

Cambiar la forma de un array sin alterar sus datos.

**Ejemplo 1:** Reshape Básico

In [ ]:
array = np.arange(12)
reshaped_array = array.reshape(3, 4)
print("Array reestructurado:\n", reshaped_array)


**Ejemplo 2:** Reshape con -1

In [ ]:
# NumPy calcula automáticamente el tamaño faltante
reshaped_array = array.reshape(2, -1)
print("Array reestructurado con -1:\n", reshaped_array)


**Ejercicios**

Convierte un array de forma (6,) en uno de forma (2, 3).


Dado un array de forma (4, 3), conviértelo en uno de forma (2, 2, 3).


Aplana un array multidimensional a un array unidimensional.

### 6.2. Transposición

Intercambia los ejes de un array.

**Ejemplo 1:** Transposición de Matriz

In [ ]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])
transposed_matrix = matrix.T
print("Matriz original:\n", matrix)
print("Matriz transpuesta:\n", transposed_matrix)


**Ejemplo 2:** Transposición de Arrays de Mayor Dimensión

In [ ]:
array = np.arange(24).reshape(2, 3, 4)
transposed_array = array.transpose(1, 0, 2)
print("Array transpuesto:\n", transposed_array.shape)


**Ejercicios**

Transpón una matriz de forma (5, 3).


Dado un array de forma (2, 3, 4), reorganiza sus ejes para obtener un array de forma (4, 2, 3).


Verifica que la transposición de una matriz simétrica es igual a la matriz original.

### 6.3. Concatenación y División de Arrays

Combina o divide arrays.

**Ejemplo 1:** Concatenación

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Concatenación unidimensional
concat_array = np.concatenate((a, b))
print("Array concatenado:", concat_array)

# Concatenación bidimensional
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])

concat_2d = np.concatenate((array1, array2), axis=0)
print("Array 2D concatenado:\n", concat_2d)


**Ejemplo 2:** División


In [ ]:
# División en arrays más pequeños
split_array = np.array_split(concat_array, 3)
print("Arrays divididos:", split_array)


**Ejercicios**

Une dos matrices de forma (2, 2) para crear una de forma (2, 4).


Divide un array de forma (12,) en tres arrays iguales.


Combina verticalmente dos arrays de forma (3, 2).

## 7. Broadcasting

El broadcasting permite realizar operaciones entre arrays de diferentes formas.

**Ejemplo 1:** Suma con Broadcasting

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])

result = a + b
print("Resultado de broadcasting:\n", result)


**Ejemplo 2:** Multiplicación con Broadcasting

In [ ]:
array = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 2

result = array * scalar
print("Multiplicación por escalar:\n", result)


Ejercicios

Suma un vector de forma (3,) a una matriz de forma (3, 3).


Multiplica cada columna de una matriz de forma (4, 3) por un vector de forma (3,).


Resta un escalar de todos los elementos de un array.


## 8. Álgebra Lineal

NumPy proporciona funciones avanzadas para realizar operaciones de álgebra lineal.



### 8.1. Producto Punto y Producto Cruz

**Ejemplo 1:** Producto Punto


In [ ]:
vector1 = np.array([1, 2])
vector2 = np.array([3, 4])

dot_product = np.dot(vector1, vector2)
print("Producto punto:", dot_product)


**Ejemplo 2:** Producto Cruz

In [ ]:
vector3 = np.array([1, 0, 0])
vector4 = np.array([0, 1, 0])

cross_product = np.cross(vector3, vector4)
print("Producto cruz:", cross_product)


**Ejercicios**

Calcula el producto punto de dos vectores de dimensión 3.


Encuentra el producto cruz de los vectores [2, 3, 4] y [5, 6, 7].


Verifica que el producto punto de dos vectores perpendiculares es cero.

### 8.2. Operaciones con Matrices

**Ejemplo 1:**  Multiplicación de Matrices

In [ ]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[2, 0], [1, 2]])

product = np.matmul(matrix1, matrix2)
print("Producto de matrices:\n", product)


**Ejemplo 2:** Inversa y Determinante

In [ ]:
matrix = np.array([[4, 7], [2, 6]])

# Inversa
inverse = np.linalg.inv(matrix)
print("Inversa de la matriz:\n", inverse)

# Determinante
determinant = np.linalg.det(matrix)
print("Determinante de la matriz:", determinant)


**Ejercicios**

Calcula el determinante de una matriz de 3x3.


Encuentra la matriz inversa de una matriz cuadrada.


Verifica que el producto de una matriz y su inversa es la matriz identidad.

### 8.3. Sistemas de Ecuaciones Lineales

Resuelve sistemas de ecuaciones lineales utilizando NumPy.


